export const UI_CONSTANTS = {
  CHAT_PANEL: {
    DEFAULT_WIDTH: 400,
    MAX_WIDTH: 1200,
    MIN_WIDTH: 300,
    RESIZE_HANDLE_WIDTH: 4,
  },
  NODE: {
    DEFAULT_WIDTH: 200,
    EXPANDED_WIDTH: 280,
    DEFAULT_HEIGHT: 100,
    EXPANDED_HEIGHT: 150,
    HANDLE_SIZE: 10,
  },
  GRAPH: {
    DEFAULT_ZOOM: 0.8,
    MIN_ZOOM: 0.1,
    MAX_ZOOM: 2,
    RANK_SEPARATION: {
      DEFAULT: 100,
      EXPANDED: 150,
    },
    NODE_SEPARATION: {
      DEFAULT: 60,
      EXPANDED: 100,
    },
  },
  ANIMATION: {
    FADE_DURATION: 500,
    TRANSITION_DURATION: 300,
    FIT_VIEW_DURATION: 400,
  },
  DASHBOARD: {
    MAX_HEIGHT: 400,
    BADGE_HEIGHT: 16,
    BADGE_MIN_WIDTH: 16,
  },
  MESSAGE: {
    MAX_WIDTH: 800,
    CONTEXT_MAX_WIDTH: 750,
    LINE_CLAMP: 2,
  },
} as const